# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 421b26c6bce4ac4d8debe515461116e79e5420d284fb847e9424f8a57909d91dd31d5ac928184a8a7f73cc81db4e783a18728d4a82e6180ec0727fa9b7774c52

test:
  secret_key_base: e53b31d2640366602a016dcfcc28be57472f30984fcbb98e41a065a8b4d09643b844f4040902c9482633d2d3bdde9ac24b939bb02863738d174db1c4b439ab1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
